name: Train + benchmark model

on:
  pull_request:
    branches:
      - main

jobs:
  train-and-benchmark-mnist:
    runs-on: titan

    steps:
    - uses: actions/checkout@v4

    - name: Check current directory
      run: pwd

    - name: Install alma package
      run: pip install . 

    - name: Setup data
      run: |
        cd examples/mnist/data
        ./setup-data.sh

    - name: Train
      run: |
        cd examples/mnist
        python train.py --save-path ./model/mnist

    - name: Benchmark
      run: |
        cd examples/mnist
        mkdir -p ../results
        python mem_efficient_benchmark_rand_tensor.py

    - name: Display benchmark results
      run: |
        echo "Displaying benchmark results:"
        echo "::group::Benchmark JSON Output"
        cat examples/mnist/results/result.json
        echo "::endgroup::"

    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: examples/mnist/results/result.json
