name: Train + benchmark model

on:
  push:
    branches:
      - 'feat/actions_1'

jobs:
  train-and-benchmark:
    runs-on: titan

    steps:
    - uses: actions/checkout@v4

    - name: Check current directory
      run: pwd

    - name: Install alma package
      run: pip install . 

    - name: Setup data
      run: |
        cd examples/mnist/data
        ./setup-data.sh

    - name: Train
      run: |
        cd examples/mnist
        python train.py --save-path ./model/mnist


    - name: Benchmark 
      run: |
        cd examples/mnist
        mkdir -p ../results
        for i in {0..14}; do
          echo "Running benchmark with conversion $i"
          timeout 60s python benchmark.py --model-path=./model/mnist.pt --data-dir=data_for_inference --conversion $i > ../results/benchmark_conversion_$i.txt 2>&1 || echo "Conversion $i failed due to timeout or error" > ../results/benchmark_conversion_$i.txt
        done

    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: examples/results/