name: Train + benchmark model

on:
  push:
    branches:
      - 'feat/actions_1'

jobs:
  train-and-benchmark:
    runs-on: titan

    steps:
    - uses: actions/checkout@v4

    - name: Check current directory
      run: pwd

    - name: Install alma package
      run: pip install . 

    - name: Setup data
      run: |
        cd examples/mnist/data
        ./setup-data.sh

    - name: Train
      run: |
        cd examples/mnist
        python train.py --save-path ./model/mnist.pt

    - name: Benchmark
      run: |
        cd examples/mnist
        python benchmark.py --model-path ./model/mnist.pt    