name: label-check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
permissions:
    actions: write
    checks: write
    contents: write
    pull-requests: write
    statuses: write
jobs:
  releaseLabelCheck:
    name: Check for version label
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: major,minor,patch
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          

